#!/bin/bash
# Script to install and configure Nginx to serve "Holberton School"

# Update package list
apt-get update -y

# Install nginx
apt-get install -y nginx

# Ensure Nginx is listening on port 80 (default)
# Create custom HTML page
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart nginx without systemctl
service nginx restart

